spring.application.name=forecasting
opencage.api.key=ae71e891ad3e4994b25a799f16244794
openweathermap.api.key=6b904086651c872d0e2c58c1529d2dcb
spring.security.user.name=user
spring.security.user.password=weather123

# Enable actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ✅ Set logging level
logging.level.com.weather.forecasting=INFO


info.app.name=Weather Forecasting API
info.app.version=1.0.0
info.app.description=Secure forecast with logging and monitoring






